#ifndef _GENERIC_TORQUER_CHECKOUT_DEVICE_CFG_H_
#define _GENERIC_TORQUER_CHECKOUT_DEVICE_CFG_H_

/*
** GENERIC_TORQUER Checkout Configuration
*/
#define GENERIC_TORQUER_CFG
#define GENERIC_TORQUER_CFG_PERIOD 50000000

#endif /* _GENERIC_TORQUER_CHECKOUT_DEVICE_CFG_H_ */
