#ifndef _NOVATEL_OEM615_CHECKOUT_DEVICE_CFG_H_
#define _NOVATEL_OEM615_CHECKOUT_DEVICE_CFG_H_

/*
** NOVATEL_OEM615 Checkout Configuration
*/
#define NOVATEL_OEM615_CFG
/* Note: NOS3 uart requires matching handle and bus number */
#define NOVATEL_OEM615_CFG_STRING         "usart_1"
#define NOVATEL_OEM615_CFG_HANDLE         1
#define NOVATEL_OEM615_CFG_BAUDRATE_HZ    115200
#define NOVATEL_OEM615_CFG_MS_TIMEOUT     50
#define NOVATEL_OEM615_CFG_READ_TIMEOUT   250
#define NOVATEL_OEM615_CFG_DATA_ERROR_CNT 10
#define NOVATEL_OEM615_CFG_DEBUG

#endif /* _NOVATEL_OEM615_CHECKOUT_DEVICE_CFG_H_ */