#ifndef _GENERIC_CSS_CHECKOUT_DEVICE_CFG_H_
#define _GENERIC_CSS_CHECKOUT_DEVICE_CFG_H_

/*
** GENERIC_CSS Checkout Configuration
*/
#define GENERIC_CSS_CFG
#define GENERIC_CSS_CFG_STRING      "i2c_2"
#define GENERIC_CSS_CFG_HANDLE      2
#define GENERIC_CSS_CFG_BAUDRATE_HZ 1000
#define GENERIC_CSS_CFG_MS_TIMEOUT  250
#define GENERIC_CSS_CFG_DEBUG

#endif /* _GENERIC_CSS_CHECKOUT_DEVICE_CFG_H_ */
